### PR TITLE
Adapt to https://github.com/coq/coq/pull/19530

### PR DESCRIPTION
**Pull request by proux01**
Adapt to https://github.com/coq/coq/pull/19530
This should be backward compatible and can be merged at your convenience, before the upstream PR.

### CODE REVIEW

**Comment by proux01** [comment]
Well, ok it's backward compatible but maybe not down to 8.4 !

**Comment by proux01** [comment]
@whonore what do you want to do with this? (FWIW, I tested it successfully on 8.12 and don't have anything older at hand to know exactly when it breaks)

**Comment by whonore** [comment]
Thanks for the fix.

**Comment by proux01** [comment]
Ha, indeed that works, thanks

**Pull request merged**
