### PR TITLE
sentence parsing for bracketed goal selectors

### LINKED ISSUE #30: sentences with bracket goal selectors are misparsed
The following coq file is currently processed incorrectly:

```coq
Goal nat * unit.
  intros.
  split.
  2: { (* there should be a sentence boundary here *)
    exact tt.
  }
  exact O.
Defined.
```

See https://github.com/coq/coq/pull/6551 for context. The "Focus" syntax is now deprecated, so it would be good to support this one instead (and bedrock2 uses it...).

### PR DESCRIPTION
**Pull request by andres-erbsen-sifive**
fixes #30

### CODE REVIEW

**Comment by whonore** [comment]
Could you add a test or two to `tests/test_parse.py`?

**Comment by whonore** [comment]
And also run `black` to autoformat it

**Comment by andres-erbsen-sifive** [comment]
formatted. Could you walk me through adding a test there? I am looking at the table and haven't figured it out yet.

**Comment by whonore** [comment]
The tuples in `tests` are `(test name, list of lines to use an input, optional starting offset, expected ending offset)`. So `("multi line", ["A", "B."], (1, 1))` gives `"A\nB."` to `_get_message_range` and expects it to find the `.` on line 1, column 1 as the end.

**Comment by andres-erbsen-sifive** [comment]
now I am trying to run the tests... I run tox and see vim run for a bit, and I then get errors for various versions of python not being found, but I think the tests I wrote are not being run. What might I be missing?

**Comment by andres-erbsen-sifive** [comment]
this looks green, so I guess I got the tests right blind.

**Comment by whonore** [comment]
You need `python2.7` and `python3.6` to run the tests through tox. If you have those and it's still not working then it's possible there's some more weirdness going on since I'm not that experienced with configuring tox and I've only really confirmed it works on my own machine and in the travis tests.

Since this passed the CI tests I'll go ahead and merge.

**Pull request merged**
