### PR TITLE
add CoqJumpToError command

### PR DESCRIPTION
**Pull request by tomtomjhj**

### CODE REVIEW

**Comment by whonore** [comment]
Thanks, this looks great. I want to test it out a little and might make a couple minor edits, but I should be able to merge tomorrow.

**Comment by whonore** [comment]
Do you have a reason for jumping to the end of the error region instead of the start? If not, I think I'd prefer using the start since that seems more intuitive to me.

**Comment by tomtomjhj** [comment]
I thought the end of the error region would be closer to the part that I should edit in order to fix the error. What do you think?

**Comment by whonore** [comment]
I guess it depends on the error. In most cases I can think of the error region is just a couple words long at most anyway so it should be pretty quick to navigate to the right spot. So let's switch to the start of the region and we can always add an option or another command later if necessary.

**Comment by tomtomjhj** [comment]
all right

**Pull request merged**
