### PR TITLE
Fix for no attribute decode

### PR DESCRIPTION
**Pull request by Cypher1**
Fixes https://github.com/whonore/Coqtail/issues/70, still experiencing unexpected hangs when working on files, coq is unable to make progress past the first definition (though CoqIDE continues without issue).

### CODE REVIEW

**Comment by Cypher1** [comment]
Also looks like your CI isn't 100%. Getting 
```
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

ERROR: InvocationError for command /home/travis/build/whonore/Coqtail/ci/install-coq.sh pytest-coq88-py27 .tox/pytest-coq88-py27/tmp (exited with code 1)

___________________________________ summary 
```

In some failures.

I can look into using six instead of falling back to normal strings but it'll likely be a few days till I get to it.

**Comment by whonore** [comment]
That's fine, there's no rush. I can also just make the change myself if you end up not having time.
As for the CI I've known for a while that it's a bit flaky. Those `'nixpkgs' not found errors` only happen sometimes and tend to go away if you just restart the job. I've just been living with it but it's probably about time to actually fix it.

**Comment by Cypher1** [comment]
Converted this to use six, still not fixing the halting problem but I can get the first expression to check.

**Comment by Cypher1** [comment]
Surprising, I thought it was a dictionary. How's that?

**Comment by whonore** [comment]
In neovim it's a `RemoteMap` object and in vim it's an `options` object. They both provide a `dict`-like API with `__(g/s)etitem__` but only `RemoteMap` has a `get` method. Anyway, the changes look good, thanks.

**Pull request merged**
